export const themeDark = '#006be6';
export const theme = '#4B9EFF';
export const themeLight = '#cce2ff';
export const loaderColor = themeDark;
export const headerTint = 'white';

export const drawerHeader = theme;
export const button = theme;
export const buttonCancel = themeDark;
export const floatingCross = 'rgba(7, 8, 8, 0.7)';
export const floatingCrossTint = 'white';
export const background = 'white';
export const fieldBorder = '#c2bdbd';
export const fieldBackground = '#FAFAFA';
export const textError = 'red';
export const textLight = '#cdc9c9';
export const textMedium = 'gray';
export const textDark = 'rgba(7, 8, 8, 0.88)';
export const thumbnail = '#D8D8D8';
export const lineLight = '#E6E6E6';
export const lineMedium = 'gray';
export const lineDark = 'black';
export const iconLight = '#c2bdbd';
export const iconMedium = 'gray';
export const iconDark = theme;
export const thumbTrackOn = '#04B431';
export const thumbTrackOff = '#c2bdbd';
export const tabBar = '#f9f8f4';
export const facebookButton = '#3B5998'
export const googleButton = '#DB4437'

export const black = 'black';
export const gray = 'gray';
export const white = 'white';
export const red = '#FA5858';
export const green = 'green';
export const blue = '#1373e2';
export const orange = '#cf8b32';
export const purple = 'purple';
export const yellow = 'yellow';
export const pink = 'pink';